// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('robobar', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(843, 777)
    await driver.findElement(By.xpath("//div[2]/button")).click()
    await driver.findElement(By.xpath("//tr[2]/td[3]/div/div/div[2]/button")).click()
    await driver.findElement(By.xpath("//tr[3]/td[3]/div/div/div[2]/button")).click()
    await driver.findElement(By.css(".btn-success")).click()
    await driver.findElement(By.id("ageInput")).click()
    await driver.findElement(By.id("ageInput")).sendKeys("21")
    await driver.findElement(By.css(".btn-success")).click()
  })
})
