// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test-total', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test-total', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(867, 686)
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    await driver.findElement(By.css(".btn-success")).click()
    vars["cantRobacola"] = await driver.findElement(By.css(".ng-scope:nth-child(1) > .ng-binding:nth-child(2)")).getText()
    vars["totalRobacola"] = await driver.findElement(By.css(".ng-scope:nth-child(1) > .ng-binding:nth-child(4)")).getText()
    assert(vars["cantRobacola"].toString() == "1")
    assert(vars["totalRobacola"].toString() == "€1.25")
    vars["cantRobobeer"] = await driver.findElement(By.css(".ng-scope:nth-child(2) > .ng-binding:nth-child(2)")).getText()
    vars["totalRoboBeer"] = await driver.findElement(By.css(".ng-scope:nth-child(2) > .ng-binding:nth-child(4)")).getText()
    assert(vars["cantRobobeer"].toString() == "1")
    assert(vars["totalRoboBeer"].toString() == "€2.00")
    vars["cantWine"] = await driver.findElement(By.css(".ng-scope:nth-child(3) > .ng-binding:nth-child(2)")).getText()
    vars["totalWine"] = await driver.findElement(By.css(".ng-scope:nth-child(3) > .ng-binding:nth-child(4)")).getText()
    assert(vars["cantWine"].toString() == "1")
    assert(vars["totalWine"].toString() == "€3.00")
  })
})
